#!/bin/bash
# Calls 'docker ps' for each node and prints it to screen.

for i in `./get_inventory  | jq '._meta.hostvars | with_entries(select(.key|match("compute"; "i")))[].ansible_ssh_host' -r`
do 
  ssh centos@$i 'sudo docker ps'
done
