---

- hosts: localhost
  gather_facts: no
  tasks:

  - name: get the username running the deploy
    become: false
    local_action: command whoami
    register: local_username

  #- debug: var=local_username

  - name: create computes
    os_server:
      state: absent
      name: "{{item}}"
      image: 368d1a0d-cc90-4190-9225-a16004deaad3
      key_name: autoscaling_abaco
      timeout: 200
      flavor: m1.tiny
      nics:
        - net-id: e34992da-2361-4b12-9c05-d41680f90fc0
      meta:
        group: mpackard-computes
      auto_ip: no
    with_items:
      - "{{local_username.stdout}}-compute"
      - "{{local_username.stdout}}-compute1"
      - "{{local_username.stdout}}-compute2"
      - "{{local_username.stdout}}-compute3"
      - "{{local_username.stdout}}-compute4"
      - "{{local_username.stdout}}-compute5"
      - "{{local_username.stdout}}-compute6"
      - "{{local_username.stdout}}-compute7"
      - "{{local_username.stdout}}-compute8"
      - "{{local_username.stdout}}-compute9"
      - "{{local_username.stdout}}-compute10"
      - "{{local_username.stdout}}-compute11"
      - "{{local_username.stdout}}-compute12"
      - "{{local_username.stdout}}-compute13"

  - name: create servers
    os_server:
      state: absent
      name: "{{item}}"
      image: 368d1a0d-cc90-4190-9225-a16004deaad3
      key_name: autoscaling_abaco
      timeout: 200
      flavor: m1.tiny
      nics:
        - net-id: e34992da-2361-4b12-9c05-d41680f90fc0
      meta:
        group: mpackard-servers
      auto_ip: no
    with_items:
      - "{{local_username.stdout}}-server1"

