#!/bin/bash
# Deletes any node with "compute" in the name.

./get_inventory  | jq '._meta.hostvars | with_entries(select(.key|match("compute"; "i")))[].openstack_id' -r | xargs openstack server delete
