#!/bin/bash
# Deletes any node with "mpackard-computes" in the name.

./get_inventory  | jq '._meta.hostvars | with_entries(select(.key|match("mpackard-computes"; "i")))[].openstack_id' -r | xargs openstack server delete
