#!/bin/bash
# Ask name of instance to be created and creates it. This instance is
# initialized with the perf-abaco-base image which contains the docker
# requirements and docker-compose files to deploy all abaco 
# Ask how many instances and initializes that many, placed in the
# "compute" group and named "compute#" where the # is
# the servers index. The image initialized is an image already built and ready,
# contains docker, docker images needed, and anything else to save building
# time. Should just work. Initializes OpenStack "m1.medium" nodes with given
# security key.

echo Instance Name?
read Instance_Name

img="31f734ae-76e7-4e90-91d5-97e4f84d4d7f" # Abaco Base Image
nic="e34992da-2361-4b12-9c05-d41680f90fc0"
key="autoscaling_abaco"
flav="m1.quad"

openstack server create --flavor $flav --image $img --nic net-id=$nic --security-group default --key-name $key --property "group=abaco" Instance_Name
