#!/bin/bash

x="mpackard-compute"

img="368d1a0d-cc90-4190-9225-a16004deaad3"
nic="e34992da-2361-4b12-9c05-d41680f90fc0"
key="autoscaling_abaco"
#flav="m1.small"
#flav="m1.tiny"
flav="m1.medium"
#num="--min 99 --max 99"
num="--min 12 --max 12"
#num="--min 1 --max 1"
#num="--min 2 --max 2"

echo openstack server create --flavor $flav --image $img --nic net-id=$nic --security-group default --key-name $key --property "group=mpackard-computes" $num $x


