---

- hosts: localhost
  gather_facts: no
  tasks:

  - name: create computes
    os_server:
      state: present
      name: "{{item}}"
      image: 5e559e1c-4915-457e-bb02-bdc939a4232c
      key_name: autoscaling_abaco
      timeout: 200
      flavor: m1.tiny
      nics:
        - net-id: e34992da-2361-4b12-9c05-d41680f90fc0
      meta:
        group: computes
      auto_ip: no
    with_items:
      - compute1
      - compute2
      - compute3
      - compute4


  - name: create servers
    os_server:
      state: present
      name: "{{item}}"
      image: 5e559e1c-4915-457e-bb02-bdc939a4232c
      key_name: autoscaling_abaco
      timeout: 200
      flavor: m1.tiny
      nics:
        - net-id: e34992da-2361-4b12-9c05-d41680f90fc0
      meta:
        group: servers
      auto_ip: no
    with_items:
      - server1

