#!/bin/bash
# Ask how many instances and initializes that many, placed in the
# "compute" group and named "compute#" where the # is
# the servers index. The image initialized is an image already built and ready,
# contains docker, docker images needed, and anything else to save building
# time. Should just work. Initializes OpenStack "m1.medium" nodes with given
# security key.

echo How many instances?
read num_of_instances

x="compute1"

img="af777776-b8e4-49c6-9da2-57e4a5e8f073" # Image is perf-abaco-compute. Base for computes
nic="e34992da-2361-4b12-9c05-d41680f90fc0"
key="autoscaling_abaco"
flav="m1.medium"
num="--min $num_of_instances --max $num_of_instances"

openstack server create --flavor $flav --image $img --nic net-id=$nic --security-group default --key-name $key --property "group=compute" $num $x
