# Sets up Abaco on given nodes. Just an docker-compose up after importing said
# docker-compose-compute.yml file and abaco.conf file from ../abaco_files.
# To change TAG, you must change the TAG in this file, but also in the local
# abaco.conf file. For instance, both must read "DEV2" if you want things to
# work.
---

- hosts: all
  gather_facts: no
  become: true
  vars:
    abaco_host_id: "{{  ansible_ssh_host.split('.')[3] }}"
  tasks:
  - name: Gather facts for first time
    setup:
  
  - name: get the username running the deploy
    become: false
    local_action: command whoami
    register: local_username

  - name: get the homedir of the user running the deploy
    become: false
    local_action: command echo $HOME
    register: local_homedir

  - fail:
      msg: "please do not run as root"
    when: local_username.stdout == "root"

  - name: ensure docker is running
    service: name=docker state=started enabled=yes
 
  - name: abaco.conf
    template:
      src: "{{local_homedir.stdout}}/abaco-autoscaling/deployment/abaco_files/abaco.conf"
      dest: /home/apim/abaco.conf
      owner: apim

  - name: docker-compose-compute.yml  
    template:
      src: "{{local_homedir.stdout}}/abaco-autoscaling/deployment/abaco_files/docker-compose-compute.yml"
      dest: /home/apim/docker-compose-compute.yml
      owner: apim

  - name: docker compose up 
    become: yes
    become_user: apim
    environment:
      abaco_path: /home/apim
      TAG: dev
    shell: /usr/local/bin/docker-compose -f docker-compose-compute.yml up -d
    args:
      chdir: /home/apim
